# Generated by Django 2.2 on 2019-04-15 00:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('elevation', models.IntegerField()),
                ('point', django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=4326)),
            ],
        ),
    ]
